### ISSUE TITLE
do not allow duplicate emails to vote

### ISSUE THREAD

**Issue by devanbenz** [BitsAndBytesBookClub/bits-and-bytes-bot#3]
Currently when the email input modal pops up there is no validation on the backend to verify that the same email has voted only 1 time. Please fix this issue. We check the email right here: https://github.com/devanbenz/bits-and-bytes-bot/blob/9da74c8f839d22300dff2fd8f98d2ca319b5d42d/main.go#L48 the email is stored in the global state object so you can check to see if its already stored in memory.

**Comment by kiabq** [comment]
I got this one o7

**Comment by devanbenz** [comment]
all yours sir o7

**Comment by devanbenz** [comment]
For sanitation please don't forget to link your PR to this issue :D

**Comment by kiabq** [comment]
Completed in #22
